networks:
  frontend:
  backend:

services:
  mongo:
    image: mongo:5
    networks:
      - backend
    volumes:
      - "./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/corona_travel --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    ports:
      - 27017:27017

  facts:
    build:
      dockerfile: ./Dockerfile
      args:
        SRC_PATH: "./src/facts"
        APP_PATH: "./facts"
        ASGI_APP: "facts.app:app"
    environment:
      MONGO_URL: mongodb://mongo/corona_travel
      LOG_LEVEL: DEBUG
    networks:
      - backend
    ports:
      - 12341:1234

  media:
    build:
      dockerfile: ./Dockerfile
      args:
        SRC_PATH: "./src/media"
        APP_PATH: "./media"
        ASGI_APP: "media.app:app"
    environment:
      MONGO_URL: mongodb://mongo/corona_travel
      LOG_LEVEL: DEBUG
    networks:
      - backend
    ports:
      - 12342:1234

  places:
    build:
      dockerfile: ./Dockerfile
      args:
        SRC_PATH: "./src/places"
        APP_PATH: "./places"
        ASGI_APP: "places.app:app"
    environment:
      MONGO_URL: mongodb://mongo/corona_travel
      LOG_LEVEL: DEBUG
    networks:
      - backend
    ports:
      - 12343:1234

  quizes:
    build:
      dockerfile: ./Dockerfile
      args:
        SRC_PATH: "./src/quizes"
        APP_PATH: "./quizes"
        ASGI_APP: "quizes.app:app"
    environment:
      MONGO_URL: mongodb://mongo/corona_travel
      LOG_LEVEL: DEBUG
    networks:
      - backend
    ports:
      - 12344:1234



